// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awuadhofwkegouccnlen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dWFkaG9md2tlZ291Y2NubGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODI3MjksImV4cCI6MjA2ODk1ODcyOX0.In1vF231TS3LHYgtFBrtaiRuAw0B94mbOjVz5NKPszY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});